# Generated by Django 5.2.12 on 2026-09-29 04:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0022_add_matching_indexes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_auto_approve_enabled', models.BooleanField(default=False, help_text='Global system setting for auto-approving new mentorship match requests.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Settings',
                'verbose_name_plural': 'System Settings',
            },
        ),
        migrations.CreateModel(
            name='CoordinatorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_auto_approve_enabled', models.BooleanField(default=False, help_text='If enabled, newly created mentorship pairings are automatically approved without manual review.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='coordinator_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Coordinator Profile',
                'verbose_name_plural': 'Coordinator Profiles',
            },
        ),
    ]
