# Generated by Django 5.2.12 on 2026-09-29 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0023_systemsettings_coordinatorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='coordinatorprofile',
            name='is_auto_verify_enabled',
            field=models.BooleanField(default=False, help_text='If enabled, newly registered users (mentors and mentees) are automatically approved and verified without manual review.'),
        ),
        migrations.AddField(
            model_name='systemsettings',
            name='is_auto_verify_enabled',
            field=models.BooleanField(default=False, help_text='Global system setting for automatically verifying and approving newly registered users (mentors and mentees).'),
        ),
    ]
