# Generated by Django 5.2.12 on 2026-09-29 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0022_replace_bsit_curriculum'),
        ('profiles', '0023_systemsettings_coordinatorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='menteementorrequest',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='menteementorrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], db_index=True, default='PENDING', max_length=20),
        ),
        migrations.AddIndex(
            model_name='menteementorrequest',
            index=models.Index(fields=['status', '-created_at'], name='matching_mmr_status_created'),
        ),
    ]
