from django.urls import path, re_path
from drf_spectacular.views import SpectacularAPIView, SpectacularSwaggerView

from .controllers.account_controller import (
    health,
    csrf,
    auth_login,
    auth_forgot_password,
    auth_password_reset_confirm,
    auth_google,
    auth_logout,
    auth_refresh,
    check_lockout,
    unified_auth_register,
    auth_verify_email,
    VerifyEmailView,
    auth_resend_verification,
    me,
    update_account,
    upload_avatar,
    upload_cover,
    update_bio,
    update_tags,
    send_password_change_code,
    verify_password_change_code,
    change_password_with_code,
    tag_suggestions,
    questionnaire_options,
    update_mentee_profile,
    update_mentee_matching_profile,
    update_mentor_profile,
    complete_profile,
    complete_onboarding,
    user_preferences,
    upload_user_document,
)
from .controllers.matching_controller import (
    run_matching,
    mentee_recommendations,
    mentee_choose_mentor,
    mentor_requests,
    mentor_accept_mentee,
    my_mentor,
    mentor_profile_by_user_id,
    admin_pairings,
)
from .controllers.approvals_controller import (
    pending_list,
    approve_mentor,
    reject_mentor,
    approve_mentee,
    reject_mentee,
)
from .controllers.coordinator_controller import (
    coordinator_approvals,
    pending_mentors as coordinator_pending_mentors,
    approve_mentor as coordinator_approve_mentor,
    reject_mentor as coordinator_reject_mentor,
    pending_users as coordinator_pending_users,
    approve_user as coordinator_approve_user,
    reject_user as coordinator_reject_user,
    coordinator_auto_approve,
)
from .controllers.announcements_controller import (
    announcements_list,
    announcement_create,
    announcement_soft_delete,
    comments_list,
    comment_create,
)
from .controllers.backup_controller import (
    backup_list,
    backup_create,
    backup_download,
    backup_restore,
    backup_restore_by_id,
    backup_delete,
)
from .controllers.drive_controller import (
    drive_upload,
    drive_list,
    drive_connected,
)
from .controllers.activity_controller import activity_logs_list, activity_logs_export
from .controllers.search_controller import search, user_public_profile
from .controllers.posts_controller import (
    posts_list,
    posts_feed,
    post_detail,
    post_create,
    post_share,
    post_like,
    post_delete,
    post_comments_list,
    post_comment_create,
    gallery,
    profile_stats,
)
from .controllers.users_controller import (
    users_list,
    user_detail,
    user_create,
    user_update,
    user_activate_deactivate,
    user_delete,
    mentor_approve_reject,
    mentee_approve_reject,
)
from .views import (
    notifications_list,
    notifications_mark_all_read,
    notification_mark_read,
    notifications_unread_count,
    subjects_list,
    subject_create,
    subject_update,
    subject_delete,
    topics_list,
    topic_create,
    topic_update,
    topic_archive_toggle,
    topic_delete,
    competencies_list,
    mentees_list,
)

urlpatterns = [
    path('health/', health, name='api-health'),
    path('csrf/', csrf, name='api-csrf'),
    path('matching/run/', run_matching, name='api-matching-run'),
    path('matching/recommendations/', mentee_recommendations, name='api-matching-recommendations'),
    path('matching/mentee-recommendations/', mentee_recommendations, name='api-matching-mentee-recommendations'),
    path('matching/mentee-choose-mentor/', mentee_choose_mentor, name='api-matching-mentee-choose-mentor'),
    path('matching/mentor-requests/', mentor_requests, name='api-matching-mentor-requests'),
    path('matching/mentor-accept-mentee/', mentor_accept_mentee, name='api-matching-mentor-accept-mentee'),
    path('matching/my-mentor/', my_mentor, name='api-matching-my-mentor'),
    path('matching/mentor-profile/<int:user_id>/', mentor_profile_by_user_id, name='api-matching-mentor-profile-by-user-id'),
    path('matching/admin-pairings/', admin_pairings, name='api-matching-admin-pairings'),
    path('auth/login/', auth_login, name='api-auth-login'),
    path('auth/forgot-password/', auth_forgot_password, name='api-auth-forgot-password'),
    path('auth/password-reset-confirm/', auth_password_reset_confirm, name='api-auth-password-reset-confirm'),
    path('auth/google/', auth_google, name='api-auth-google'),
    path('auth/google/login/', auth_google, name='api-auth-google-login'),
    path('auth/refresh/', auth_refresh, name='api-auth-refresh'),
    path('auth/logout/', auth_logout, name='api-auth-logout'),
    path('auth/check-lockout/', check_lockout, name='api-auth-check-lockout'),
    path('auth/register/', unified_auth_register, name='api-auth-register'),
    re_path(r'^verify-email/?$', VerifyEmailView.as_view(), name='api-verify-email'),
    re_path(r'^auth/verify-email/?$', VerifyEmailView.as_view(), name='api-auth-verify-email'),
    path('auth/resend-verification/', auth_resend_verification, name='api-auth-resend-verification'),
    path('me/', me, name='api-me'),
    path('me/update/', update_account, name='api-me-update'),
    path('me/avatar/', upload_avatar, name='api-me-avatar'),
    path('me/cover/', upload_cover, name='api-me-cover'),
    path('account/documents/upload/', upload_user_document, name='api-account-documents-upload'),
    path('user/documents/upload/', upload_user_document, name='api-user-documents-upload'),
    path('me/complete-profile/', complete_profile, name='api-me-complete-profile'),
    path('user/complete-onboarding/', complete_onboarding, name='api-user-complete-onboarding'),
    path('user/onboarding/', complete_onboarding, name='api-user-onboarding'),
    path('user/preferences/', user_preferences, name='api-user-preferences'),
    path('me/complete_profile/', complete_profile, name='api-me-complete-profile-alias'),
    path('me/mentee-profile/', update_mentee_profile, name='api-me-mentee-profile'),
    path('me/mentee-matching/', update_mentee_matching_profile, name='api-me-mentee-matching'),
    path('me/mentor-profile/', update_mentor_profile, name='api-me-mentor-profile'),
    path('me/bio/', update_bio, name='api-me-bio'),
    path('me/tags/', update_tags, name='api-me-tags'),
    path('me/password-code/send/', send_password_change_code, name='api-me-password-code-send'),
    path('me/password-code/verify/', verify_password_change_code, name='api-me-password-code-verify'),
    path('me/password-code/change/', change_password_with_code, name='api-me-password-code-change'),
    path('tags/suggestions/', tag_suggestions, name='api-tags-suggestions'),
    path('questionnaire/options/', questionnaire_options, name='api-questionnaire-options'),
    path('approvals/pending/', pending_list, name='api-approvals-pending'),
    path('approvals/approve-mentor/', approve_mentor, name='api-approvals-approve-mentor'),
    path('approvals/reject-mentor/', reject_mentor, name='api-approvals-reject-mentor'),
    path('approvals/approve-mentee/', approve_mentee, name='api-approvals-approve-mentee'),
    path('approvals/reject-mentee/', reject_mentee, name='api-approvals-reject-mentee'),
    path('coordinator/approvals/', coordinator_approvals, name='api-coordinator-approvals'),
    path('coordinator/pending-mentors/', coordinator_pending_mentors, name='api-coordinator-pending-mentors'),
    path('coordinator/approve-mentor/<int:user_id>/', coordinator_approve_mentor, name='api-coordinator-approve-mentor'),
    path('coordinator/reject-mentor/<int:user_id>/', coordinator_reject_mentor, name='api-coordinator-reject-mentor'),
    path('coordinator/pending-users/', coordinator_pending_users, name='api-coordinator-pending-users'),
    path('coordinator/users/<int:user_id>/approve/', coordinator_approve_user, name='api-coordinator-user-approve'),
    path('coordinator/users/<int:user_id>/reject/', coordinator_reject_user, name='api-coordinator-user-reject'),
    path('coordinator/auto-approve/', coordinator_auto_approve, name='api-coordinator-auto-approve'),
    path('coordinator/settings/auto-approve/', coordinator_auto_approve, name='api-coordinator-settings-auto-approve'),
    path('notifications/', notifications_list, name='api-notifications-list'),
    path('notifications/unread-count/', notifications_unread_count, name='api-notifications-unread-count'),
    path('notifications/mark-all-read/', notifications_mark_all_read, name='api-notifications-mark-all-read'),
    path('notifications/<int:notification_id>/read/', notification_mark_read, name='api-notifications-read'),
    path('subjects/', subjects_list, name='api-subjects-list'),
    path('subjects/create/', subject_create, name='api-subjects-create'),
    path('subjects/<int:subject_id>/update/', subject_update, name='api-subjects-update'),
    path('subjects/<int:subject_id>/delete/', subject_delete, name='api-subjects-delete'),
    path('topics/', topics_list, name='api-topics-list'),
    path('topics/create/', topic_create, name='api-topics-create'),
    path('topics/<int:topic_id>/update/', topic_update, name='api-topics-update'),
    path('topics/<int:topic_id>/status/', topic_archive_toggle, name='api-topics-status'),
    path('topics/<int:topic_id>/delete/', topic_delete, name='api-topics-delete'),
    path('competencies/', competencies_list, name='api-competencies-list'),
    path('mentees/', mentees_list, name='api-mentees-list'),
    path('announcements/', announcements_list, name='api-announcements-list'),
    path('announcements/create/', announcement_create, name='api-announcements-create'),
    path('announcements/<int:announcement_id>/delete/', announcement_soft_delete, name='api-announcements-delete'),
    path('comments/<str:target_type>/<int:target_id>/', comments_list, name='api-comments-list'),
    path('comments/create/', comment_create, name='api-comments-create'),
    path('backup/', backup_list, name='api-backup-list'),
    path('backup/create/', backup_create, name='api-backup-create'),
    path('backup/restore/', backup_restore, name='api-backup-restore'),
    path('backup/<str:backup_id>/download/', backup_download, name='api-backup-download'),
    path('backup/<str:backup_id>/restore/', backup_restore_by_id, name='api-backup-restore-by-id'),
    path('backup/<str:backup_id>/delete/', backup_delete, name='api-backup-delete'),
    path('drive/connected/', drive_connected, name='api-drive-connected'),
    path('drive/upload/', drive_upload, name='api-drive-upload'),
    path('drive/files/', drive_list, name='api-drive-list'),
    path('activity-logs/', activity_logs_list, name='api-activity-logs'),
    path('activity-logs/export/', activity_logs_export, name='api-activity-logs-export'),
    path('search/', search, name='api-search'),
    path('users/<int:user_id>/profile/', user_public_profile, name='api-user-public-profile'),
    path('posts/', posts_list, name='api-posts-list'),
    path('posts/feed/', posts_feed, name='api-posts-feed'),
    path('posts/create/', post_create, name='api-posts-create'),
    path('posts/<int:post_id>/', post_detail, name='api-posts-detail'),
    path('posts/<int:post_id>/like/', post_like, name='api-posts-like'),
    path('posts/<int:post_id>/share/', post_share, name='api-posts-share'),
    path('posts/<int:post_id>/delete/', post_delete, name='api-posts-delete'),
    path('posts/<int:post_id>/comments/', post_comments_list, name='api-posts-comments-list'),
    path('posts/<int:post_id>/comments/create/', post_comment_create, name='api-posts-comments-create'),
    path('gallery/', gallery, name='api-gallery'),
    path('profile-stats/', profile_stats, name='api-profile-stats'),
    path('users/', users_list, name='api-users-list'),
    path('users/create/', user_create, name='api-users-create'),
    path('users/<int:user_id>/', user_detail, name='api-users-detail'),
    path('users/<int:user_id>/update/', user_update, name='api-users-update'),
    path('users/<int:user_id>/activate-deactivate/', user_activate_deactivate, name='api-users-activate-deactivate'),
    path('users/<int:user_id>/delete/', user_delete, name='api-users-delete'),
    path('users/<int:user_id>/mentor-approve/', mentor_approve_reject, name='api-users-mentor-approve'),
    path('users/<int:user_id>/mentee-approve/', mentee_approve_reject, name='api-users-mentee-approve'),
    path('schema/', SpectacularAPIView.as_view(permission_classes=[]), name='api-schema'),
    path('docs/', SpectacularSwaggerView.as_view(url_name='api-schema', permission_classes=[]), name='api-docs'),
]
